// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vikiProject.Models;

namespace vikiProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210816191158_newUpdates2")]
    partial class newUpdates2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("vikiProject.Models.DownloadLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadLink");
                });

            modelBuilder.Entity("vikiProject.Models.Drama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfEpisodes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dramas");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadLinkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DramaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadLinkId");

                    b.HasIndex("DramaId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.HasOne("vikiProject.Models.DownloadLink", "DownloadLink")
                        .WithMany()
                        .HasForeignKey("DownloadLinkId");

                    b.HasOne("vikiProject.Models.Drama", "Drama")
                        .WithMany("Episodes")
                        .HasForeignKey("DramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownloadLink");

                    b.Navigation("Drama");
                });

            modelBuilder.Entity("vikiProject.Models.Drama", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
