// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vikiProject.Models;

namespace vikiProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210822182035_updted")]
    partial class updted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("vikiProject.Models.DownloadLink", b =>
                {
                    b.Property<int>("DramaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoLink")
                        .HasColumnType("TEXT");

                    b.HasKey("DramaId", "EpisodeNumber", "Quality");

                    b.HasIndex("EpisodeNumber", "DramaId");

                    b.ToTable("DownloadLinks");
                });

            modelBuilder.Entity("vikiProject.Models.Drama", b =>
                {
                    b.Property<int>("DramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfEpisodes")
                        .HasColumnType("INTEGER");

                    b.HasKey("DramaId");

                    b.ToTable("Dramas");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DramaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EpisodeNumber", "DramaId");

                    b.HasIndex("DramaId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("vikiProject.Models.OtherName", b =>
                {
                    b.Property<int>("NameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DramaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NameId");

                    b.HasIndex("DramaId");

                    b.ToTable("OtherNames");
                });

            modelBuilder.Entity("vikiProject.Models.DownloadLink", b =>
                {
                    b.HasOne("vikiProject.Models.Episode", "Episode")
                        .WithMany("DownloadLinks")
                        .HasForeignKey("EpisodeNumber", "DramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.HasOne("vikiProject.Models.Drama", "Drama")
                        .WithMany("Episodes")
                        .HasForeignKey("DramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drama");
                });

            modelBuilder.Entity("vikiProject.Models.OtherName", b =>
                {
                    b.HasOne("vikiProject.Models.Drama", "Drama")
                        .WithMany("OtherNames")
                        .HasForeignKey("DramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drama");
                });

            modelBuilder.Entity("vikiProject.Models.Drama", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("OtherNames");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.Navigation("DownloadLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
