// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vikiProject.Models;

namespace vikiProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("vikiProject.Models.DownloadLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DramaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeDramaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeDramaId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeNumber2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeNumber1", "EpisodeDramaId");

                    b.HasIndex("EpisodeNumber2", "EpisodeDramaId1");

                    b.ToTable("DownloadLinks");
                });

            modelBuilder.Entity("vikiProject.Models.Drama", b =>
                {
                    b.Property<int>("DramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("DramaId");

                    b.ToTable("Dramas");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DramaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EpisodeNumber", "DramaId");

                    b.HasIndex("DramaId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("vikiProject.Models.DownloadLink", b =>
                {
                    b.HasOne("vikiProject.Models.Episode", null)
                        .WithMany("DownloadLinks")
                        .HasForeignKey("EpisodeNumber1", "EpisodeDramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vikiProject.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeNumber2", "EpisodeDramaId1");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.HasOne("vikiProject.Models.Drama", null)
                        .WithMany("Episodes")
                        .HasForeignKey("DramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vikiProject.Models.Drama", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("vikiProject.Models.Episode", b =>
                {
                    b.Navigation("DownloadLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
